// examples/realtime-quickstart-vue/src/App.vue
<template>
  <div style="text-align: center">
    <a-space style="padding: 20px">
      <a-button
        type="primary"
        :disabled="isConnected || isConnecting"
        @click="handleConnectClick"
      >
        连接
      </a-button>
      <a-button :disabled="!isConnected" @click="handleInterrupt">
        打断
      </a-button>
      <a-button danger :disabled="!isConnected" @click="handleDisconnect">
        断开
      </a-button>
      <a-button
        v-if="audioEnabled"
        :disabled="!isConnected"
        @click="toggleMicrophone"
      >
        静音
      </a-button>
      <a-button v-else :disabled="!isConnected" @click="toggleMicrophone">
        取消静音
      </a-button>
    </a-space>
    <br />
    <a-space direction="vertical">
      <a-space v-if="isSupportVideo">
        <div
          id="local-player"
          style="width: 400px; height: 400px; border: 1px solid #ccc"
        ></div>
      </a-space>
      <a-space>
        <div
          style="
            margin-top: 20px;
            padding: 20px;
            max-height: 600px;
            width: 400px;
            overflow-y: auto;
            border: 1px solid #ccc;
          "
        >
          <h3>实时语音回复</h3>
          <a-list :data-source="messageList">
            <template #renderItem="{ item }">
              <a-list-item style="text-align: left">
                {{ item }}
              </a-list-item>
            </template>
          </a-list>
        </div>
      </a-space>
    </a-space>
  </div>
</template>

<script lang="ts" setup>
import { ref, onUnmounted } from 'vue';
import { message } from 'ant-design-vue';
import {
  EventNames,
  RealtimeAPIError,
  RealtimeClient,
  RealtimeError,
  RealtimeUtils,
} from '@coze/realtime-api';
import { CozeAPI, COZE_CN_BASE_URL, ChatEventType } from '@coze/api';
import {
  useTokenWithPat,
  useTokenWithWeb,
  useTokenWithJWT,
  useTokenWithDevice,
  useTokenWithPKCE,
} from './hooks/index';

const botId = '7428177321599221810';

const client = ref<RealtimeClient | null>(null);
const messageList = ref<string[]>([]);
const isConnecting = ref(false);
const isConnected = ref(false);
const audioEnabled = ref(true);
const isSupportVideo = ref(false);

const { getToken } = useTokenWithPat();
// const { getToken } = useTokenWithWeb();

async function getVoices() {
  const api = new CozeAPI({
    token: getToken,
    baseURL: COZE_CN_BASE_URL,
    allowPersonalAccessTokenInBrowser: true,
  });

  const voices = await api.audio.voices.list();
  return voices.voice_list;
}

async function initClient() {
  const permission = await RealtimeUtils.checkDevicePermission(true);
  if (!permission.audio) {
    throw new Error('需要麦克风访问权限');
  }
  isSupportVideo.value = permission.video;

  const voices = await getVoices();

  client.value = new RealtimeClient({
    accessToken: getToken,
    botId,
    connectorId: '1024',
    voiceId: voices.length > 0 ? voices[0].voice_id : undefined,
    allowPersonalAccessTokenInBrowser: true,
    debug: true,
    videoConfig: permission.video
      ? {
          renderDom: 'local-player',
        }
      : undefined,
  });

  handleMessageEvent();
}

const handleMessageEvent = () => {
  let lastEvent: any;

  client.value?.on(EventNames.ALL_SERVER, (eventName, event: any) => {
    if (
      event.event_type !== ChatEventType.CONVERSATION_MESSAGE_DELTA &&
      event.event_type !== ChatEventType.CONVERSATION_MESSAGE_COMPLETED
    ) {
      return;
    }
    const content = event.data.content;

    if (lastEvent?.event_type === ChatEventType.CONVERSATION_MESSAGE_DELTA) {
      messageList.value[messageList.value.length - 1] += content;
    } else if (event.event_type === ChatEventType.CONVERSATION_MESSAGE_DELTA) {
      messageList.value.push(content);
    }
    lastEvent = event;
  });
};

const handleConnectClick = async () => {
  isConnecting.value = true;
  try {
    await handleConnect();
  } finally {
    isConnecting.value = false;
  }
};

const handleConnect = async () => {
  try {
    if (!client.value) {
      await initClient();
    }
    await client.value?.connect();
    isConnected.value = true;
  } catch (error) {
    console.error(error);
    if (error instanceof RealtimeAPIError) {
      switch (error.code) {
        case RealtimeError.CREATE_ROOM_ERROR:
          message.error(`创建房间失败: ${error.message}`);
          break;
        case RealtimeError.CONNECTION_ERROR:
          message.error(`加入房间失败: ${error.message}`);
          break;
        case RealtimeError.DEVICE_ACCESS_ERROR:
          message.error(`获取设备失败: ${error.message}`);
          break;
        default:
          message.error(`连接错误: ${error.message}`);
      }
    } else {
      message.error('连接错误：' + error);
    }
  }
};

const handleInterrupt = () => {
  try {
    client.value?.interrupt();
  } catch (error) {
    message.error('打断失败：' + error);
  }
};

const handleDisconnect = () => {
  try {
    client.value?.disconnect();
    client.value?.clearEventHandlers();
    client.value = null;
    isConnected.value = false;
  } catch (error) {
    message.error('断开失败：' + error);
  }
};

const toggleMicrophone = async () => {
  try {
    await client.value?.setAudioEnable(!audioEnabled.value);
    audioEnabled.value = !audioEnabled.value;
  } catch (error) {
    message.error('切换麦克风状态失败：' + error);
  }
};

onUnmounted(() => {
  handleDisconnect();
});
</script>

// examples/realtime-quickstart-react/src/App.tsx
/* eslint-disable */
import { useRef, useState } from 'react';
import {
  EventNames,
  RealtimeAPIError,
  RealtimeClient,
  RealtimeError,
  RealtimeUtils,
} from '@coze/realtime-api';
import { Button, Space, List, message } from 'antd';
import { CozeAPI, COZE_CN_BASE_URL, ChatEventType } from '@coze/api';
import {
  useTokenWithPat,
  useTokenWithDevice,
  useTokenWithJWT,
  useTokenWithPKCE,
  useTokenWithWeb,
} from './hooks';

const botId = '7457832409259147***';

function App() {
  const clientRef = useRef<RealtimeClient | null>(null);
  // 实时语音回复消息列表
  const [messageList, setMessageList] = useState<string[]>([]);
  // 是否正在连接
  const [isConnecting, setIsConnecting] = useState(false);
  // 是否已连接
  const [isConnected, setIsConnected] = useState(false);
  // 是否开启麦克风
  const [audioEnabled, setAudioEnabled] = useState(true);
  // 是否支持视频
  const [isSupportVideo, setIsSupportVideo] = useState(false);

  const { getToken } = useTokenWithPat();
  // const { getToken } = useTokenWithDevice();
  // const { getToken } = useTokenWithJWT();
  // const { getToken } = useTokenWithPKCE();
  // const { getToken } = useTokenWithWeb();
  async function getVoices() {
    const api = new CozeAPI({
      token: getToken,
      baseURL: COZE_CN_BASE_URL,
      allowPersonalAccessTokenInBrowser: true,
    });

    const voices = await api.audio.voices.list();
    return voices.voice_list;
  }

  async function initClient() {
    const permission = await RealtimeUtils.checkDevicePermission(true);
    if (!permission.audio) {
      throw new Error('需要麦克风访问权限');
    }
    // 记录是否支持视频
    setIsSupportVideo(permission.video);

    // 获取可用音色列表(可选)
    const voices = await getVoices();

    const client = new RealtimeClient({
      accessToken: getToken,
      botId,
      connectorId: '1024',
      voiceId: voices.length > 0 ? voices[0].voice_id : undefined,
      allowPersonalAccessTokenInBrowser: true, // 可选：允许在浏览器中使用个人访问令牌
      debug: true,
      videoConfig: permission.video
        ? {
            renderDom: 'local-player',
          }
        : undefined,
    });

    clientRef.current = client;

    handleMessageEvent();
  }

  const handleMessageEvent = async () => {
    let lastEvent: any;

    clientRef.current?.on(EventNames.ALL_SERVER, (eventName, event: any) => {
      if (
        event.event_type !== ChatEventType.CONVERSATION_MESSAGE_DELTA &&
        event.event_type !== ChatEventType.CONVERSATION_MESSAGE_COMPLETED
      ) {
        return;
      }
      const content = event.data.content;
      setMessageList(prev => {
        // 如果上一个事件是增量更新，则附加到最后一条消息
        if (
          lastEvent?.event_type === ChatEventType.CONVERSATION_MESSAGE_DELTA
        ) {
          return [...prev.slice(0, -1), prev[prev.length - 1] + content];
        }
        // 否则添加新消息
        if (event.event_type === ChatEventType.CONVERSATION_MESSAGE_DELTA) {
          return [...prev, content];
        }
        return prev;
      });
      lastEvent = event;
    });
  };

  const handleConnect = async () => {
    try {
      if (!clientRef.current) {
        await initClient();
      }
      await clientRef.current?.connect();
      setIsConnected(true);
    } catch (error) {
      console.error(error);
      if (error instanceof RealtimeAPIError) {
        switch (error.code) {
          case RealtimeError.CREATE_ROOM_ERROR:
            message.error(`创建房间失败: ${error.message}`);
            break;
          case RealtimeError.CONNECTION_ERROR:
            message.error(`加入房间失败: ${error.message}`);
            break;
          case RealtimeError.DEVICE_ACCESS_ERROR:
            message.error(`获取设备失败: ${error.message}`);
            break;
          default:
            message.error(`连接错误: ${error.message}`);
        }
      } else {
        message.error('连接错误：' + error);
      }
    }
  };

  const handleInterrupt = () => {
    try {
      clientRef.current?.interrupt();
    } catch (error) {
      message.error('打断失败：' + error);
    }
  };

  const handleDisconnect = () => {
    try {
      clientRef.current?.disconnect();
      clientRef.current?.clearEventHandlers();
      clientRef.current = null;
      setIsConnected(false);
    } catch (error) {
      message.error('断开失败：' + error);
    }
  };

  const toggleMicrophone = async () => {
    try {
      await clientRef.current?.setAudioEnable(!audioEnabled);
      setAudioEnabled(!audioEnabled);
    } catch (error) {
      message.error('切换麦克风状态失败：' + error);
    }
  };

  return (
    <div style={{ textAlign: 'center' }}>
      <Space style={{ padding: '20px' }}>
        <Button
          type="primary"
          disabled={isConnected || isConnecting}
          onClick={() => {
            setIsConnecting(true);
            handleConnect().finally(() => {
              setIsConnecting(false);
            });
          }}
        >
          连接
        </Button>
        <Button disabled={!isConnected} onClick={handleInterrupt}>
          打断
        </Button>
        <Button danger disabled={!isConnected} onClick={handleDisconnect}>
          断开
        </Button>
        {audioEnabled ? (
          <Button disabled={!isConnected} onClick={toggleMicrophone}>
            静音
          </Button>
        ) : (
          <Button disabled={!isConnected} onClick={toggleMicrophone}>
            取消静音
          </Button>
        )}
      </Space>
      <br />
      <Space direction="vertical">
        {isSupportVideo && (
          <Space>
            <div
              id="local-player"
              style={{
                width: 400,
                height: 400,
                border: '1px solid #ccc',
              }}
            ></div>
          </Space>
        )}
        <Space>
          <div
            style={{
              marginTop: '20px',
              padding: '20px',
              maxHeight: '600px',
              width: '400px',
              overflowY: 'auto',
              border: '1px solid #ccc',
            }}
          >
            <h3>实时语音回复</h3>
            <List
              dataSource={messageList}
              renderItem={(message, index) => (
                <List.Item key={index} style={{ textAlign: 'left' }}>
                  {message}
                </List.Item>
              )}
            />
          </div>
        </Space>
      </Space>
    </div>
  );
}

export default App;
